-- FitGuide 数据库初始化脚本
-- 适用版本：MySQL 5.7.18
-- 执行前请先选择目标数据库。本脚本面向空库，只应执行一次。

SET NAMES utf8mb4 COLLATE utf8mb4_general_ci;
SET time_zone = '+08:00';

CREATE TABLE fit_catalog (
    id          TINYINT UNSIGNED NOT NULL COMMENT '目录主键，固定为1',
    version     BIGINT UNSIGNED NOT NULL COMMENT '动作目录数据版本',
    disclaimer  VARCHAR(500) NOT NULL COMMENT '健身安全免责声明',
    created_at  DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    updated_at  DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
                ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
    PRIMARY KEY (id)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_general_ci
  COMMENT = 'FitGuide动作目录元数据表';

CREATE TABLE fit_exercise (
    id                 VARCHAR(64) NOT NULL COMMENT '动作唯一标识，使用kebab-case英文名称',
    name               VARCHAR(100) NOT NULL COMMENT '动作中文名称',
    category           VARCHAR(32) NOT NULL COMMENT '训练部位分类',
    equipment          VARCHAR(100) NOT NULL COMMENT '动作所需器械名称',
    level              VARCHAR(16) NOT NULL COMMENT '动作难度，当前为初级或中级',
    primary_muscles    JSON NOT NULL COMMENT '主要刺激肌群JSON数组',
    secondary_muscles  JSON NOT NULL COMMENT '辅助刺激肌群JSON数组，无数据时为空数组',
    image_url          VARCHAR(512) NOT NULL COMMENT '动作封面地址，支持cloud或HTTP(S)地址',
    gif_url            VARCHAR(512) NOT NULL COMMENT '动作演示地址，支持cloud或HTTP(S)地址',
    steps              JSON NOT NULL COMMENT '按执行顺序保存的动作步骤JSON数组',
    cautions           JSON NOT NULL COMMENT '安全注意事项JSON数组',
    sort_order         INT UNSIGNED NOT NULL COMMENT '展示顺序，对应源JSON数组顺序',
    enabled            BOOLEAN NOT NULL DEFAULT TRUE COMMENT '启用状态：1启用，0停用',
    created_at         DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    updated_at         DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
                       ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
    PRIMARY KEY (id),
    UNIQUE KEY uk_fit_exercise_sort_order (sort_order),
    KEY idx_fit_exercise_list (enabled, sort_order)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_general_ci
  COMMENT = 'FitGuide健身动作表';


INSERT INTO fit_catalog (id, version, disclaimer)
VALUES (1, 1, '内容仅供一般健身动作参考；首次使用器械时请让教练确认座椅、限位和重量设置。');

INSERT INTO fit_exercise (
    id,
    name,
    category,
    equipment,
    level,
    primary_muscles,
    secondary_muscles,
    image_url,
    gif_url,
    steps,
    cautions,
    sort_order,
    enabled
) VALUES
    ('seated-lat-pulldown', '坐姿高位下拉', '背部', '高位下拉器', '初级', '["背阔肌"]', '["肱二头肌","后三角肌"]', 'https://7072-prod-d4gi5hg2s057d6cfc-1466119943.tcb.qcloud.la/exercises/seated-lat-pulldown/seated-lat-pulldown.jpg', 'https://7072-prod-d4gi5hg2s057d6cfc-1466119943.tcb.qcloud.la/exercises/seated-lat-pulldown/seated-lat-pulldown.gif', '["调节大腿垫并坐稳，双手正握横杆，握距略宽于肩。","保持胸口抬起和躯干稳定，沉肩后让肘部向下移动，将横杆拉向上胸。","缓慢伸直手臂回到起始位，保持肩部受控。"]', '["不要把横杆拉到颈后。","避免借助后仰和摆动完成动作。"]', 1, 1),
    ('seated-cable-row', '坐姿划船', '背部', '坐姿划船器', '初级', '["背阔肌","菱形肌","斜方肌中束"]', '["肱二头肌","后三角肌"]', 'https://7072-prod-d4gi5hg2s057d6cfc-1466119943.tcb.qcloud.la/exercises/seated-cable-row/seated-cable-row.jpg', 'https://7072-prod-d4gi5hg2s057d6cfc-1466119943.tcb.qcloud.la/exercises/seated-cable-row/seated-cable-row.gif', '["双脚踩稳踏板，握住把手并保持脊柱自然中立。","肩胛骨向后收紧，肘部贴近身体，将把手拉向下肋部。","控制手臂前伸，肩部保持稳定，不要弓背。"]', '["不要用身体前后摆动带动重量。","避免耸肩或过度后仰。"]', 2, 1),
    ('machine-chest-press', '坐姿推胸', '胸部', '坐姿推胸机', '初级', '["胸大肌"]', '["前三角肌","肱三头肌"]', 'https://7072-prod-d4gi5hg2s057d6cfc-1466119943.tcb.qcloud.la/exercises/machine-chest-press/machine-chest-press.jpg', 'https://7072-prod-d4gi5hg2s057d6cfc-1466119943.tcb.qcloud.la/exercises/machine-chest-press/machine-chest-press.gif', '["调节座椅，使把手与胸部中段大致齐平，背部贴紧靠垫。","手腕保持中立，双手同时向前推至手臂接近伸直。","缓慢屈肘回到起始位，保持肩胛稳定。"]', '["手肘不要完全锁死。","避免含胸或让肩部向前顶出。"]', 3, 1),
    ('machine-shoulder-press', '器械肩推', '肩部', '肩部推举机', '初级', '["三角肌"]', '["肱三头肌","斜方肌上束"]', 'https://7072-prod-d4gi5hg2s057d6cfc-1466119943.tcb.qcloud.la/exercises/machine-shoulder-press/machine-shoulder-press.jpg', 'https://7072-prod-d4gi5hg2s057d6cfc-1466119943.tcb.qcloud.la/exercises/machine-shoulder-press/machine-shoulder-press.gif', '["调节座椅，使把手位于肩部附近，背部贴住靠垫。","保持手腕与肘部对齐，双手同时向上推举。","手臂接近伸直后缓慢下放，回到肘部略低于肩的位置。"]', '["不要锁死肘关节。","避免塌腰或用腿蹬地借力。"]', 4, 1),
    ('leg-press', '45°腿举', '腿部', '45°腿举机', '初级', '["股四头肌","臀大肌"]', '["腘绳肌","小腿肌群"]', 'https://7072-prod-d4gi5hg2s057d6cfc-1466119943.tcb.qcloud.la/exercises/leg-press/leg-press.jpg', 'https://7072-prod-d4gi5hg2s057d6cfc-1466119943.tcb.qcloud.la/exercises/leg-press/leg-press.gif', '["背部和臀部贴紧靠垫，双脚与肩同宽踩在踏板中部。","膝盖朝脚尖方向弯曲，解除保险后将踏板平稳推出。","腿部接近伸直后缓慢下放，在骨盆仍贴住靠垫的位置停止。"]', '["膝关节不要锁死或向内扣。","下放过深导致腰部离开靠垫时应缩小幅度。"]', 5, 1),
    ('seated-leg-extension', '坐姿腿屈伸', '腿部', '腿屈伸机', '初级', '["股四头肌"]', '[]', 'https://7072-prod-d4gi5hg2s057d6cfc-1466119943.tcb.qcloud.la/exercises/seated-leg-extension/seated-leg-extension.jpg', 'https://7072-prod-d4gi5hg2s057d6cfc-1466119943.tcb.qcloud.la/exercises/seated-leg-extension/seated-leg-extension.gif', '["调节靠背，让膝关节与器械转轴对齐，滚垫位于小腿下端。","抓稳把手，双腿同时向前伸展至接近伸直。","缓慢屈膝下放重量，保持臀部和背部贴住座椅。"]', '["不要甩动重量或猛然锁膝。","出现膝前侧疼痛时立即停止。"]', 6, 1),
    ('seated-leg-curl', '坐姿腿弯举', '腿部', '坐姿腿弯举机', '初级', '["腘绳肌"]', '["腓肠肌"]', 'https://7072-prod-d4gi5hg2s057d6cfc-1466119943.tcb.qcloud.la/exercises/seated-leg-curl/seated-leg-curl.jpg', 'https://7072-prod-d4gi5hg2s057d6cfc-1466119943.tcb.qcloud.la/exercises/seated-leg-curl/seated-leg-curl.gif', '["调节座椅，使膝关节对齐器械转轴，并固定大腿压垫。","小腿后侧贴住滚垫，双腿同时向下、向后弯曲。","到达舒适幅度后缓慢伸膝，让重量受控回位。"]', '["不要让臀部离开座椅。","避免快速弹回配重。"]', 7, 1),
    ('rope-triceps-pushdown', '绳索三头下压', '手臂', '龙门架高位滑轮', '初级', '["肱三头肌"]', '[]', 'https://7072-prod-d4gi5hg2s057d6cfc-1466119943.tcb.qcloud.la/exercises/rope-triceps-pushdown/rope-triceps-pushdown.jpg', 'https://7072-prod-d4gi5hg2s057d6cfc-1466119943.tcb.qcloud.la/exercises/rope-triceps-pushdown/rope-triceps-pushdown.gif', '["将绳索连接高位滑轮，双脚站稳，上臂贴近身体。","保持肘部位置不变，伸直手臂向下压，底端稍微分开绳索。","缓慢屈肘回到约九十度，保持配重受控。"]', '["不要让肘部前后移动。","避免身体下压或摆动借力。"]', 8, 1),
    ('pec-deck-fly', '蝴蝶机夹胸', '胸部', '蝴蝶机', '初级', '["胸大肌"]', '["前三角肌"]', 'https://7072-prod-d4gi5hg2s057d6cfc-1466119943.tcb.qcloud.la/exercises/pec-deck-fly/pec-deck-fly.jpg', 'https://7072-prod-d4gi5hg2s057d6cfc-1466119943.tcb.qcloud.la/exercises/pec-deck-fly/pec-deck-fly.gif', '["调节座椅，使上臂与肩部大致同高，背部贴紧靠垫。","前臂贴住垫板，保持肘部弯曲，双臂同时向胸前合拢。","短暂停顿后缓慢打开双臂，在胸部仍有张力的位置停止。"]', '["不要让手臂过度后展。","避免耸肩或借助身体前倾。"]', 9, 1),
    ('reverse-pec-deck-fly', '反向蝴蝶机飞鸟', '肩部', '反向蝴蝶机', '初级', '["后三角肌","菱形肌","斜方肌中束"]', '[]', 'https://7072-prod-d4gi5hg2s057d6cfc-1466119943.tcb.qcloud.la/exercises/reverse-pec-deck-fly/reverse-pec-deck-fly.jpg', 'https://7072-prod-d4gi5hg2s057d6cfc-1466119943.tcb.qcloud.la/exercises/reverse-pec-deck-fly/reverse-pec-deck-fly.gif', '["面向靠垫坐下，胸部贴住靠垫，双手握住与肩同高的把手。","肘部保持微屈，双臂向身体两侧和后方展开，肩胛骨轻轻收紧。","缓慢让双臂回到前方，保持胸部不离开靠垫。"]', '["不要耸肩或大幅挺腰。","避免用手臂快速甩动重量。"]', 10, 1),
    ('smith-machine-squat', '史密斯机深蹲', '腿部', '史密斯机', '初级', '["股四头肌","臀大肌"]', '["腘绳肌","竖脊肌"]', 'https://7072-prod-d4gi5hg2s057d6cfc-1466119943.tcb.qcloud.la/exercises/smith-machine-squat/smith-machine-squat.jpg', 'https://7072-prod-d4gi5hg2s057d6cfc-1466119943.tcb.qcloud.la/exercises/smith-machine-squat/smith-machine-squat.gif', '["将横杆放在上背部，双脚与肩同宽并略放在横杆前方，设好安全限位。","保持脚掌贴地和膝盖朝向脚尖，屈髋屈膝下蹲至舒适深度。","脚掌均匀发力站起，回到膝关节接近伸直的位置。"]', '["横杆不要压在颈椎上。","膝盖不要内扣，腰背不要失去中立。"]', 11, 1),
    ('assisted-pull-up', '辅助引体向上', '背部', '辅助引体向上机', '初级', '["背阔肌"]', '["肱二头肌","斜方肌下束","后三角肌"]', 'https://7072-prod-d4gi5hg2s057d6cfc-1466119943.tcb.qcloud.la/exercises/assisted-pull-up/assisted-pull-up.jpg', 'https://7072-prod-d4gi5hg2s057d6cfc-1466119943.tcb.qcloud.la/exercises/assisted-pull-up/assisted-pull-up.gif', '["选择辅助重量，双手握住上方把手，双膝稳定放在辅助踏板上。","先沉肩，再将肘部向下拉，让身体上升至下巴接近把手高度。","缓慢伸直手臂下降，保持踏板和身体受控。"]', '["上下踏板时先抓稳把手。","不要摆腿或用惯性冲到顶部。"]', 12, 1),
    ('hip-abduction', '坐姿髋外展', '臀部', '髋外展机', '初级', '["臀中肌","臀小肌"]', '["臀大肌"]', 'https://7072-prod-d4gi5hg2s057d6cfc-1466119943.tcb.qcloud.la/exercises/hip-abduction/hip-abduction.jpg', 'https://7072-prod-d4gi5hg2s057d6cfc-1466119943.tcb.qcloud.la/exercises/hip-abduction/hip-abduction.gif', '["坐稳并将背部贴住靠垫，让膝盖外侧接触垫板。","保持脚部放稳，双膝同时向外推至可控幅度。","缓慢让双腿回到起始位，不让配重突然落下。"]', '["不要用身体前后摆动。","避免为了更大幅度而旋转骨盆。"]', 13, 1),
    ('hip-adduction', '坐姿髋内收', '腿部', '髋内收机', '初级', '["大腿内收肌群"]', '[]', 'https://7072-prod-d4gi5hg2s057d6cfc-1466119943.tcb.qcloud.la/exercises/hip-adduction/hip-adduction.jpg', 'https://7072-prod-d4gi5hg2s057d6cfc-1466119943.tcb.qcloud.la/exercises/hip-adduction/hip-adduction.gif', '["坐稳并将大腿内侧贴住垫板，在舒适范围内设置起始开合角度。","保持背部贴住靠垫，双腿同时向中间夹拢。","缓慢打开双腿回到起始位，持续控制配重。"]', '["不要一开始就设置过大的开合角度。","腹股沟出现疼痛时立即停止。"]', 14, 1),
    ('seated-calf-raise', '坐姿提踵', '小腿', '坐姿提踵机', '初级', '["比目鱼肌"]', '["腓肠肌"]', 'https://7072-prod-d4gi5hg2s057d6cfc-1466119943.tcb.qcloud.la/exercises/seated-calf-raise/seated-calf-raise.jpg', 'https://7072-prod-d4gi5hg2s057d6cfc-1466119943.tcb.qcloud.la/exercises/seated-calf-raise/seated-calf-raise.gif', '["前脚掌踩稳踏板，脚跟悬空，将大腿压垫固定在膝盖上方。","放下安全挡杆，抬高脚跟完成踝关节跖屈。","在顶端短暂停顿，再缓慢降低脚跟至舒适拉伸位置。"]', '["前脚掌不要离开踏板。","避免快速弹动或脚踝向内外翻。"]', 15, 1),
    ('roman-chair-back-extension', '罗马椅背伸', '下背部', '45°罗马椅', '初级', '["竖脊肌","臀大肌"]', '["腘绳肌"]', 'https://7072-prod-d4gi5hg2s057d6cfc-1466119943.tcb.qcloud.la/exercises/roman-chair-back-extension/roman-chair-back-extension.jpg', 'https://7072-prod-d4gi5hg2s057d6cfc-1466119943.tcb.qcloud.la/exercises/roman-chair-back-extension/roman-chair-back-extension.gif', '["脚踝固定在滚垫下方，让髋部位于支撑垫前缘，双臂交叉放在胸前。","保持脊柱自然中立，从髋部折叠并缓慢降低上身。","收紧臀部和下背部，将身体抬回一条直线后停止。"]', '["不要在顶端过度后仰。","出现腰部锐痛时立即停止。"]', 16, 1),
    ('hack-squat', '哈克深蹲', '腿部', '哈克深蹲机', '初级', '["股四头肌","臀大肌"]', '["腘绳肌"]', 'https://7072-prod-d4gi5hg2s057d6cfc-1466119943.tcb.qcloud.la/exercises/hack-squat/hack-squat.jpg', 'https://7072-prod-d4gi5hg2s057d6cfc-1466119943.tcb.qcloud.la/exercises/hack-squat/hack-squat.gif', '["肩部和背部贴紧滑动靠垫，双脚与肩同宽踩稳踏板。","解除保险后屈膝下放滑台，膝盖保持朝向脚尖。","下蹲至舒适深度后踩住踏板站起，膝关节不要锁死。"]', '["脚跟不要离开踏板。","避免膝盖内扣或腰背离开靠垫。"]', 17, 1),
    ('lying-leg-curl', '卧式腿弯举', '腿部', '卧式腿弯举机', '初级', '["腘绳肌"]', '["腓肠肌"]', 'https://7072-prod-d4gi5hg2s057d6cfc-1466119943.tcb.qcloud.la/exercises/lying-leg-curl/lying-leg-curl.jpg', 'https://7072-prod-d4gi5hg2s057d6cfc-1466119943.tcb.qcloud.la/exercises/lying-leg-curl/lying-leg-curl.gif', '["俯卧在靠垫上，让膝关节对齐转轴，滚垫位于脚踝后方。","保持髋部贴住靠垫，双腿同时弯曲，将脚跟拉向臀部。","到达舒适幅度后缓慢伸膝，控制滚垫回到起始位。"]', '["不要抬起髋部或过度拱腰。","避免快速弹回配重。"]', 18, 1),
    ('machine-hip-thrust', '臀推机臀推', '臀部', '臀推机', '初级', '["臀大肌"]', '["腘绳肌"]', 'https://7072-prod-d4gi5hg2s057d6cfc-1466119943.tcb.qcloud.la/exercises/machine-hip-thrust/machine-hip-thrust.jpg', 'https://7072-prod-d4gi5hg2s057d6cfc-1466119943.tcb.qcloud.la/exercises/machine-hip-thrust/machine-hip-thrust.gif', '["上背部贴住靠垫，双脚与肩同宽踩地，将髋部压垫固定好。","收紧腹部并通过脚跟发力，将髋部抬至躯干与大腿接近一条直线。","顶端收紧臀部后缓慢降低髋部，保持膝盖稳定。"]', '["不要在顶端过度挺腰。","膝盖不要内扣，压垫不要压在腹部。"]', 19, 1),
    ('cable-glute-kickback', '绳索后踢腿', '臀部', '龙门架低位滑轮', '初级', '["臀大肌"]', '["腘绳肌"]', 'https://7072-prod-d4gi5hg2s057d6cfc-1466119943.tcb.qcloud.la/exercises/cable-glute-kickback/cable-glute-kickback.jpg', 'https://7072-prod-d4gi5hg2s057d6cfc-1466119943.tcb.qcloud.la/exercises/cable-glute-kickback/cable-glute-kickback.gif', '["将脚踝带连接低位滑轮，双手扶稳器械，支撑腿保持微屈。","保持骨盆朝前，将工作腿从髋部向后伸展。","顶端收紧臀部后缓慢回腿，保持绳索持续受力。"]', '["不要靠拱腰增加后踢幅度。","避免身体旋转或甩腿。"]', 20, 1),
    ('machine-lateral-raise', '器械侧平举', '肩部', '侧平举机', '初级', '["三角肌中束"]', '["三角肌前束","三角肌后束"]', 'https://7072-prod-d4gi5hg2s057d6cfc-1466119943.tcb.qcloud.la/exercises/machine-lateral-raise/machine-lateral-raise.jpg', 'https://7072-prod-d4gi5hg2s057d6cfc-1466119943.tcb.qcloud.la/exercises/machine-lateral-raise/machine-lateral-raise.gif', '["坐稳并将背部贴住靠垫，让上臂外侧贴住肘垫。","保持肩部下沉，双肘向身体两侧抬起至接近肩高。","缓慢降低肘垫回到身体两侧，持续控制配重。"]', '["不要耸肩或用身体摆动。","手肘不要明显高于肩部。"]', 21, 1),
    ('preacher-curl-machine', '牧师凳弯举', '手臂', '牧师凳弯举机', '初级', '["肱二头肌"]', '["肱肌","前臂肌群"]', 'https://7072-prod-d4gi5hg2s057d6cfc-1466119943.tcb.qcloud.la/exercises/preacher-curl-machine/preacher-curl-machine.jpg', 'https://7072-prod-d4gi5hg2s057d6cfc-1466119943.tcb.qcloud.la/exercises/preacher-curl-machine/preacher-curl-machine.gif', '["调节座椅，让上臂完整贴住斜垫，双手反握把手。","保持上臂不动，屈肘将把手拉向肩部。","顶端停顿后缓慢伸肘，回到手臂接近伸直的位置。"]', '["不要让上臂离开斜垫。","底端不要猛然锁死肘关节。"]', 22, 1),
    ('assisted-dip', '辅助双杠臂屈伸', '手臂', '辅助引体/双杠机', '初级', '["肱三头肌","胸大肌下部"]', '["三角肌前束"]', 'https://7072-prod-d4gi5hg2s057d6cfc-1466119943.tcb.qcloud.la/exercises/assisted-dip/assisted-dip.jpg', 'https://7072-prod-d4gi5hg2s057d6cfc-1466119943.tcb.qcloud.la/exercises/assisted-dip/assisted-dip.gif', '["选择辅助重量，双手握住双杠，双膝稳定放在辅助踏板上。","保持肩部下沉并屈肘下降，直到肘部约为九十度。","向下推压把手伸直手臂，让身体平稳回到顶部。"]', '["上下踏板时先抓稳把手。","肩部不适时不要下降过深。"]', 23, 1),
    ('cable-chest-fly', '绳索夹胸', '胸部', '龙门架', '初级', '["胸大肌"]', '["三角肌前束"]', 'https://7072-prod-d4gi5hg2s057d6cfc-1466119943.tcb.qcloud.la/exercises/cable-chest-fly/cable-chest-fly.jpg', 'https://7072-prod-d4gi5hg2s057d6cfc-1466119943.tcb.qcloud.la/exercises/cable-chest-fly/cable-chest-fly.gif', '["将两侧滑轮调至胸部高度，前后站立并保持躯干轻微前倾。","肘部保持微屈，双手沿弧线向胸前合拢。","胸前短暂停顿后缓慢打开双臂，保持绳索受控。"]', '["不要让手臂过度后展。","避免耸肩或通过身体摆动拉动重量。"]', 24, 1),
    ('machine-ab-crunch', '器械卷腹', '核心', '腹肌训练机', '初级', '["腹直肌"]', '["腹斜肌"]', 'https://7072-prod-d4gi5hg2s057d6cfc-1466119943.tcb.qcloud.la/exercises/machine-ab-crunch/machine-ab-crunch.jpg', 'https://7072-prod-d4gi5hg2s057d6cfc-1466119943.tcb.qcloud.la/exercises/machine-ab-crunch/machine-ab-crunch.gif', '["坐稳并固定双脚，让肩部压垫贴合上身，双手轻握把手。","收紧腹部，将胸廓向骨盆方向卷曲并带动压垫前移。","缓慢回到脊柱中立位，保持臀部不离开座椅。"]', '["不要只靠手臂拉动把手。","回程不要过度后仰或突然放回配重。"]', 25, 1),
    ('rotary-torso', '坐姿转体', '核心', '躯干旋转机', '初级', '["腹内斜肌","腹外斜肌"]', '[]', 'https://7072-prod-d4gi5hg2s057d6cfc-1466119943.tcb.qcloud.la/exercises/rotary-torso/rotary-torso.jpg', 'https://7072-prod-d4gi5hg2s057d6cfc-1466119943.tcb.qcloud.la/exercises/rotary-torso/rotary-torso.gif', '["坐稳并用腿垫固定骨盆，胸部贴住旋转垫，双手握住把手。","保持骨盆朝前，用躯干带动旋转垫转向一侧。","到达可控幅度后缓慢回到正中，再换另一侧训练。"]', '["不要用手臂猛拉或快速甩动。","腰部疼痛时缩小幅度或停止。"]', 26, 1),
    ('treadmill-walk-run', '跑步机快走/跑步', '有氧', '跑步机', '初级', '["股四头肌","臀大肌","腘绳肌"]', '["小腿肌群"]', 'https://7072-prod-d4gi5hg2s057d6cfc-1466119943.tcb.qcloud.la/exercises/treadmill-walk-run/treadmill-walk-run.jpg', 'https://7072-prod-d4gi5hg2s057d6cfc-1466119943.tcb.qcloud.la/exercises/treadmill-walk-run/treadmill-walk-run.gif', '["站到跑带中央并夹好安全扣，从低速开始适应跑带。","保持身体直立和自然摆臂，脚步落在身体重心附近。","结束时逐步降低速度，跑带停止后再离开机器。"]', '["不要在高速运转时跳上或跳下跑带。","不要长期抓住扶手代替正常行走姿势。"]', 27, 1),
    ('rowing-machine', '划船机划船', '有氧', '划船机', '初级', '["股四头肌","臀大肌","背阔肌"]', '["腘绳肌","斜方肌","肱二头肌"]', 'https://7072-prod-d4gi5hg2s057d6cfc-1466119943.tcb.qcloud.la/exercises/rowing-machine/rowing-machine.jpg', 'https://7072-prod-d4gi5hg2s057d6cfc-1466119943.tcb.qcloud.la/exercises/rowing-machine/rowing-machine.gif', '["固定双脚，屈膝滑到前端，手臂伸直并保持背部中立。","先蹬腿，再打开髋部，最后将把手拉向下肋部。","回程先伸手、再前倾躯干、最后屈膝滑回起始位。"]', '["不要一开始就用手臂猛拉。","避免含胸、过度后仰或膝盖向外张开。"]', 28, 1),
    ('elliptical-trainer', '椭圆机', '有氧', '椭圆机', '初级', '["股四头肌","臀大肌"]', '["腘绳肌","小腿肌群"]', 'https://7072-prod-d4gi5hg2s057d6cfc-1466119943.tcb.qcloud.la/exercises/elliptical-trainer/elliptical-trainer.jpg', 'https://7072-prod-d4gi5hg2s057d6cfc-1466119943.tcb.qcloud.la/exercises/elliptical-trainer/elliptical-trainer.gif', '["双脚踩稳踏板，双手握住活动把手，从低阻力开始。","保持身体直立，让手脚协调交替推动器械。","以均匀节奏完成训练，结束前逐步降低速度。"]', '["脚掌始终贴稳踏板。","不要耸肩或过度前倾身体。"]', 29, 1),
    ('spin-bike', '动感单车', '有氧', '动感单车', '初级', '["股四头肌","臀大肌"]', '["腘绳肌","小腿肌群"]', 'https://7072-prod-d4gi5hg2s057d6cfc-1466119943.tcb.qcloud.la/exercises/spin-bike/spin-bike.jpg', 'https://7072-prod-d4gi5hg2s057d6cfc-1466119943.tcb.qcloud.la/exercises/spin-bike/spin-bike.gif', '["调节座椅高度，使踏板最低点时膝盖仍保持微屈。","固定双脚并轻握车把，保持稳定节奏完整踩踏。","结束前降低阻力和转速，待飞轮减速后再下车。"]', '["不要让膝盖明显向内或向外偏移。","不要在飞轮高速转动时突然下车。"]', 30, 1),
    ('recumbent-bike', '卧式健身车', '有氧', '卧式健身车', '初级', '["股四头肌","臀大肌"]', '["腘绳肌","小腿肌群"]', 'https://7072-prod-d4gi5hg2s057d6cfc-1466119943.tcb.qcloud.la/exercises/recumbent-bike/recumbent-bike.jpg', 'https://7072-prod-d4gi5hg2s057d6cfc-1466119943.tcb.qcloud.la/exercises/recumbent-bike/recumbent-bike.gif', '["调节座椅，让背部贴住靠垫且腿伸出时膝盖微屈。","固定双脚，保持骨盆稳定并平顺地踩动踏板。","用可持续的阻力完成训练，结束前逐步减速。"]', '["不要让腰部离开靠垫。","不要把膝关节完全锁死。"]', 31, 1),
    ('vertical-climber', '登山机', '有氧', '垂直登山机', '初级', '["股四头肌","臀大肌","背阔肌"]', '["小腿肌群","肱三头肌"]', 'https://7072-prod-d4gi5hg2s057d6cfc-1466119943.tcb.qcloud.la/exercises/vertical-climber/vertical-climber.jpg', 'https://7072-prod-d4gi5hg2s057d6cfc-1466119943.tcb.qcloud.la/exercises/vertical-climber/vertical-climber.gif', '["双脚踩稳踏板，双手握住活动把手并保持身体直立。","用对侧手脚交替下压，保持连续的攀爬节奏。","控制动作幅度和阻力，结束时逐渐放慢。"]', '["不要只用手臂拉动身体。","上下器械时先确认踏板停止。"]', 32, 1),
    ('stair-climber', '楼梯机', '有氧', '楼梯机', '初级', '["股四头肌","臀大肌"]', '["腘绳肌","小腿肌群"]', 'https://7072-prod-d4gi5hg2s057d6cfc-1466119943.tcb.qcloud.la/exercises/stair-climber/stair-climber.jpg', 'https://7072-prod-d4gi5hg2s057d6cfc-1466119943.tcb.qcloud.la/exercises/stair-climber/stair-climber.gif', '["扶稳栏杆踏上台阶，从最低速度开始。","保持身体直立，双脚交替完整踩实每级台阶。","结束前降低速度，机器停止后再离开。"]', '["不要把身体重量长期压在扶手上。","不要踩到台阶边缘或跨越多级。"]', 33, 1),
    ('ski-erg', '滑雪机', '有氧', '滑雪机', '初级', '["背阔肌","肱三头肌","腹直肌"]', '["臀大肌","腘绳肌"]', 'https://7072-prod-d4gi5hg2s057d6cfc-1466119943.tcb.qcloud.la/exercises/ski-erg/ski-erg.jpg', 'https://7072-prod-d4gi5hg2s057d6cfc-1466119943.tcb.qcloud.la/exercises/ski-erg/ski-erg.gif', '["面向器械站立，双手握柄并举至头顶前方。","收紧核心并屈髋，将双手同步拉向大腿两侧。","控制手柄回到高位，恢复直立后重复。"]', '["不要只靠手臂猛拉。","保持背部中立，避免塌腰或过度弓背。"]', 34, 1),
    ('air-bike', '风阻自行车', '有氧', '风阻自行车', '初级', '["股四头肌","臀大肌","三角肌"]', '["腘绳肌","小腿肌群","肱三头肌"]', 'https://7072-prod-d4gi5hg2s057d6cfc-1466119943.tcb.qcloud.la/exercises/air-bike/air-bike.jpg', 'https://7072-prod-d4gi5hg2s057d6cfc-1466119943.tcb.qcloud.la/exercises/air-bike/air-bike.gif', '["调好座椅并固定双脚，双手握住活动把手。","双腿持续踩踏，同时双臂交替推拉把手。","保持均匀呼吸，结束前逐渐降低动作速度。"]', '["不要让膝盖明显内扣。","高强度冲刺后不要立即停止不动。"]', 35, 1),
    ('curved-treadmill', '无动力跑步机', '有氧', '弧形无动力跑步机', '初级', '["股四头肌","臀大肌","腘绳肌"]', '["小腿肌群"]', 'https://7072-prod-d4gi5hg2s057d6cfc-1466119943.tcb.qcloud.la/exercises/curved-treadmill/curved-treadmill.jpg', 'https://7072-prod-d4gi5hg2s057d6cfc-1466119943.tcb.qcloud.la/exercises/curved-treadmill/curved-treadmill.gif', '["扶住前方栏杆踏上弧形跑带，从中后部缓慢行走。","保持身体直立，用自然步幅带动跑带并逐渐加速。","减小步幅并移向跑带后部，完全停稳后再下机。"]', '["初次使用时不要直接冲刺。","不要跨步到跑带最前端或突然跳下。"]', 36, 1),
    ('incline-machine-chest-press', '上斜器械推胸', '胸部', '上斜推胸机', '初级', '["胸大肌上部"]', '["三角肌前束","肱三头肌"]', 'https://7072-prod-d4gi5hg2s057d6cfc-1466119943.tcb.qcloud.la/exercises/incline-machine-chest-press/incline-machine-chest-press.jpg', 'https://7072-prod-d4gi5hg2s057d6cfc-1466119943.tcb.qcloud.la/exercises/incline-machine-chest-press/incline-machine-chest-press.gif', '["调节座椅，使把手位于上胸两侧，背部贴紧靠垫。","收紧肩胛并向前上方推起把手，手臂接近伸直。","控制把手回到胸侧，保持前臂与推举方向一致。"]', '["不要耸肩或让腰部过度拱起。","肘部不要在顶端完全锁死。"]', 37, 1),
    ('decline-machine-chest-press', '下斜器械推胸', '胸部', '下斜推胸机', '初级', '["胸大肌下部"]', '["三角肌前束","肱三头肌"]', 'https://7072-prod-d4gi5hg2s057d6cfc-1466119943.tcb.qcloud.la/exercises/decline-machine-chest-press/decline-machine-chest-press.jpg', 'https://7072-prod-d4gi5hg2s057d6cfc-1466119943.tcb.qcloud.la/exercises/decline-machine-chest-press/decline-machine-chest-press.gif', '["调节座椅，使把手位于下胸两侧并让背部贴紧靠垫。","沿器械轨迹向前下方推起把手，胸部保持收紧。","缓慢屈肘回到起点，不让配重突然落下。"]', '["不要让肩部向前滚动。","使用可控重量，避免肘部过度后移。"]', 38, 1),
    ('chest-supported-row', '胸托划船', '背部', '胸托划船机', '初级', '["背阔肌","菱形肌","斜方肌中束"]', '["三角肌后束","肱二头肌"]', 'https://7072-prod-d4gi5hg2s057d6cfc-1466119943.tcb.qcloud.la/exercises/chest-supported-row/chest-supported-row.jpg', 'https://7072-prod-d4gi5hg2s057d6cfc-1466119943.tcb.qcloud.la/exercises/chest-supported-row/chest-supported-row.gif', '["调节座椅，让胸骨稳定贴住胸垫，双手握住把手。","先收紧肩胛，再将肘部沿身体两侧拉向后方。","缓慢伸直手臂回到起点，胸部始终贴住支撑垫。"]', '["不要耸肩或抬起胸部借力。","回程时不要突然放松肩胛。"]', 39, 1),
    ('single-arm-machine-row', '单臂器械划船', '背部', '单臂划船机', '初级', '["背阔肌","菱形肌"]', '["三角肌后束","肱二头肌"]', 'https://7072-prod-d4gi5hg2s057d6cfc-1466119943.tcb.qcloud.la/exercises/single-arm-machine-row/single-arm-machine-row.jpg', 'https://7072-prod-d4gi5hg2s057d6cfc-1466119943.tcb.qcloud.la/exercises/single-arm-machine-row/single-arm-machine-row.gif', '["胸部贴住支撑垫，一手握住独立把手，另一手稳定身体。","保持躯干不转动，将工作侧肘部拉向腰部。","控制把手前移至手臂伸展，完成一侧后再换边。"]', '["不要通过扭转身体增加幅度。","肩部保持下沉，不要向耳朵耸起。"]', 40, 1),
    ('straight-arm-cable-pulldown', '直臂下压', '背部', '龙门架高位滑轮', '初级', '["背阔肌","大圆肌"]', '["肱三头肌长头","腹直肌"]', 'https://7072-prod-d4gi5hg2s057d6cfc-1466119943.tcb.qcloud.la/exercises/straight-arm-cable-pulldown/straight-arm-cable-pulldown.jpg', 'https://7072-prod-d4gi5hg2s057d6cfc-1466119943.tcb.qcloud.la/exercises/straight-arm-cable-pulldown/straight-arm-cable-pulldown.gif', '["面对高位滑轮站立，双手握杆并让手臂伸向前上方。","保持肘部微屈固定，将横杆沿弧线压向大腿。","背阔肌保持张力，控制横杆回到肩部上方。"]', '["不要把动作变成肘屈伸。","避免塌腰或用身体摆动下压。"]', 41, 1),
    ('single-arm-cable-lat-pulldown', '单臂绳索下拉', '背部', '龙门架高位滑轮', '初级', '["背阔肌","大圆肌"]', '["肱二头肌","三角肌后束"]', 'https://7072-prod-d4gi5hg2s057d6cfc-1466119943.tcb.qcloud.la/exercises/single-arm-cable-lat-pulldown/single-arm-cable-lat-pulldown.jpg', 'https://7072-prod-d4gi5hg2s057d6cfc-1466119943.tcb.qcloud.la/exercises/single-arm-cable-lat-pulldown/single-arm-cable-lat-pulldown.gif', '["单膝跪在高位滑轮旁，工作手握住单柄并向上伸展。","保持躯干稳定，将肘部向下拉至身体侧后方。","缓慢伸展手臂回到高位，完成一侧后换边。"]', '["不要侧弯身体代替背部发力。","肩部不适时不要在顶端过度牵拉。"]', 42, 1),
    ('cable-face-pull', '绳索面拉', '肩部', '龙门架高位滑轮', '初级', '["三角肌后束","斜方肌中束","菱形肌"]', '["冈下肌","小圆肌"]', 'https://7072-prod-d4gi5hg2s057d6cfc-1466119943.tcb.qcloud.la/exercises/cable-face-pull/cable-face-pull.jpg', 'https://7072-prod-d4gi5hg2s057d6cfc-1466119943.tcb.qcloud.la/exercises/cable-face-pull/cable-face-pull.gif', '["将绳索调至面部高度，双手握住绳头并后退站稳。","肘部抬高，将绳索拉向额头并把两端分至耳侧。","保持肩胛受控，缓慢伸直手臂回到起点。"]', '["不要耸肩或过度后仰。","使用轻重量保持肩部外旋。"]', 43, 1),
    ('cable-lateral-raise', '绳索侧平举', '肩部', '龙门架低位滑轮', '初级', '["三角肌中束"]', '["冈上肌"]', 'https://7072-prod-d4gi5hg2s057d6cfc-1466119943.tcb.qcloud.la/exercises/cable-lateral-raise/cable-lateral-raise.jpg', 'https://7072-prod-d4gi5hg2s057d6cfc-1466119943.tcb.qcloud.la/exercises/cable-lateral-raise/cable-lateral-raise.gif', '["侧对低位滑轮站立，外侧手跨过身体握住单柄。","肘部保持微屈，将手臂向侧面抬至肩部高度。","控制手柄回到身体前方，完成一侧后换边。"]', '["不要耸肩或甩动身体。","手臂不要明显高于肩部。"]', 44, 1),
    ('cable-front-raise', '绳索前平举', '肩部', '龙门架低位滑轮', '初级', '["三角肌前束"]', '["胸大肌上部"]', 'https://7072-prod-d4gi5hg2s057d6cfc-1466119943.tcb.qcloud.la/exercises/cable-front-raise/cable-front-raise.jpg', 'https://7072-prod-d4gi5hg2s057d6cfc-1466119943.tcb.qcloud.la/exercises/cable-front-raise/cable-front-raise.gif', '["背对或跨立低位滑轮，双手在大腿前握住横杆。","保持手臂近乎伸直，将横杆向前抬至肩部高度。","躯干保持直立，缓慢将横杆放回大腿前方。"]', '["不要后仰借力。","不要耸肩或把横杆抬得过高。"]', 45, 1),
    ('cable-biceps-curl', '绳索二头弯举', '手臂', '龙门架低位滑轮', '初级', '["肱二头肌","肱肌"]', '["肱桡肌"]', 'https://7072-prod-d4gi5hg2s057d6cfc-1466119943.tcb.qcloud.la/exercises/cable-biceps-curl/cable-biceps-curl.jpg', 'https://7072-prod-d4gi5hg2s057d6cfc-1466119943.tcb.qcloud.la/exercises/cable-biceps-curl/cable-biceps-curl.gif', '["面对低位滑轮站立，反握横杆并让双臂自然下垂。","固定上臂，屈肘将横杆拉向上胸前方。","顶端收紧二头肌后缓慢伸肘回到起点。"]', '["不要向前抬起肘部。","避免摆动躯干或突然放回配重。"]', 46, 1),
    ('overhead-rope-triceps-extension', '绳索过顶臂屈伸', '手臂', '龙门架', '初级', '["肱三头肌"]', '[]', 'https://7072-prod-d4gi5hg2s057d6cfc-1466119943.tcb.qcloud.la/exercises/overhead-rope-triceps-extension/overhead-rope-triceps-extension.jpg', 'https://7072-prod-d4gi5hg2s057d6cfc-1466119943.tcb.qcloud.la/exercises/overhead-rope-triceps-extension/overhead-rope-triceps-extension.gif', '["背对滑轮分腿站立，双手握绳并将上臂固定在耳侧。","保持躯干稳定，伸直肘部将绳头推向前上方。","缓慢屈肘让绳索回到头后，保持上臂位置不变。"]', '["不要让腰部过度反弓。","肘部不要明显向两侧打开。"]', 47, 1),
    ('reverse-grip-triceps-pushdown', '反握三头下压', '手臂', '龙门架高位滑轮', '初级', '["肱三头肌"]', '["前臂屈肌群"]', 'https://7072-prod-d4gi5hg2s057d6cfc-1466119943.tcb.qcloud.la/exercises/reverse-grip-triceps-pushdown/reverse-grip-triceps-pushdown.jpg', 'https://7072-prod-d4gi5hg2s057d6cfc-1466119943.tcb.qcloud.la/exercises/reverse-grip-triceps-pushdown/reverse-grip-triceps-pushdown.gif', '["面对高位滑轮站立，以掌心向上的反握抓住短杆。","将肘部固定在身体两侧，伸肘把横杆压向大腿。","控制横杆回到下胸前方，保持手腕中立。"]', '["不要让肘部向前移动。","反握不稳时降低重量，避免手腕过度弯曲。"]', 48, 1),
    ('reverse-hack-squat', '哈克机反向深蹲', '腿部', '哈克深蹲机', '初级', '["股四头肌","臀大肌"]', '["腘绳肌"]', 'https://7072-prod-d4gi5hg2s057d6cfc-1466119943.tcb.qcloud.la/exercises/reverse-hack-squat/reverse-hack-squat.jpg', 'https://7072-prod-d4gi5hg2s057d6cfc-1466119943.tcb.qcloud.la/exercises/reverse-hack-squat/reverse-hack-squat.gif', '["面向器械站上踏板，将肩部置于肩垫下并握稳把手。","保持躯干稳定，屈髋屈膝下降至可控深度。","脚掌均匀发力伸展髋膝，沿轨道回到起点。"]', '["膝盖保持与脚尖方向一致。","不要在顶端锁死膝关节。"]', 49, 1),
    ('horizontal-leg-press', '水平腿举', '腿部', '水平腿举机', '初级', '["股四头肌","臀大肌"]', '["腘绳肌"]', 'https://7072-prod-d4gi5hg2s057d6cfc-1466119943.tcb.qcloud.la/exercises/horizontal-leg-press/horizontal-leg-press.jpg', 'https://7072-prod-d4gi5hg2s057d6cfc-1466119943.tcb.qcloud.la/exercises/horizontal-leg-press/horizontal-leg-press.gif', '["背部贴紧靠垫，双脚与肩同宽放在垂直踏板上。","屈膝让座椅或踏板平稳靠近，腰臀保持贴垫。","用全脚掌推开踏板，双腿接近伸直后缓慢返回。"]', '["不要让膝盖向内扣。","下降时不要让骨盆卷离靠垫。"]', 50, 1),
    ('standing-single-leg-curl', '站姿单腿弯举', '腿部', '站姿腿弯举机', '初级', '["腘绳肌"]', '["腓肠肌"]', 'https://7072-prod-d4gi5hg2s057d6cfc-1466119943.tcb.qcloud.la/exercises/standing-single-leg-curl/standing-single-leg-curl.jpg', 'https://7072-prod-d4gi5hg2s057d6cfc-1466119943.tcb.qcloud.la/exercises/standing-single-leg-curl/standing-single-leg-curl.gif', '["面对支撑垫站稳，将工作腿脚踝后侧贴住滚垫。","保持大腿固定，屈膝把脚跟拉向臀部。","缓慢放下滚垫至膝盖接近伸直，完成后换腿。"]', '["不要通过后仰身体抬起重量。","回程不要让配重突然落下。"]', 51, 1),
    ('glute-kickback-machine', '臀部后踢机', '臀部', '臀部后踢机', '初级', '["臀大肌"]', '["腘绳肌"]', 'https://7072-prod-d4gi5hg2s057d6cfc-1466119943.tcb.qcloud.la/exercises/glute-kickback-machine/glute-kickback-machine.jpg', 'https://7072-prod-d4gi5hg2s057d6cfc-1466119943.tcb.qcloud.la/exercises/glute-kickback-machine/glute-kickback-machine.gif', '["身体贴稳支撑垫，一脚站稳，另一脚抵住后方踏板。","收紧核心，用臀部将工作腿向后推至髋部伸展。","控制踏板回到起点，完成一侧后再换腿。"]', '["不要通过塌腰增加后踢幅度。","支撑腿保持稳定且膝盖微屈。"]', 52, 1),
    ('single-leg-machine-hip-thrust', '臀推机单腿臀推', '臀部', '臀推机', '中级', '["臀大肌"]', '["腘绳肌","腹部肌群"]', 'https://7072-prod-d4gi5hg2s057d6cfc-1466119943.tcb.qcloud.la/exercises/single-leg-machine-hip-thrust/single-leg-machine-hip-thrust.jpg', 'https://7072-prod-d4gi5hg2s057d6cfc-1466119943.tcb.qcloud.la/exercises/single-leg-machine-hip-thrust/single-leg-machine-hip-thrust.gif', '["上背贴住靠垫，髋垫固定在髋部，一脚踩稳踏板。","抬起另一条腿，用支撑侧臀部将髋部推至水平。","保持骨盆稳定，缓慢降低髋部后重复并换腿。"]', '["不要通过过度挺腰完成顶端动作。","骨盆旋转或支撑腿不稳时降低重量。"]', 53, 1),
    ('standing-calf-raise', '站姿提踵', '腿部', '站姿提踵机', '初级', '["腓肠肌","比目鱼肌"]', '[]', 'https://7072-prod-d4gi5hg2s057d6cfc-1466119943.tcb.qcloud.la/exercises/standing-calf-raise/standing-calf-raise.jpg', 'https://7072-prod-d4gi5hg2s057d6cfc-1466119943.tcb.qcloud.la/exercises/standing-calf-raise/standing-calf-raise.gif', '["前脚掌踩在踏板边缘，肩部顶住肩垫并保持膝盖微屈。","让脚跟缓慢下沉，感受小腿后侧拉伸。","以前脚掌发力将脚跟抬高，停顿后缓慢下降。"]', '["不要通过屈伸膝盖弹起重量。","脚踝保持正直，避免向内或向外翻。"]', 54, 1),
    ('single-leg-calf-raise', '单腿提踵', '腿部', '提踵台或提踵机', '中级', '["腓肠肌","比目鱼肌"]', '[]', 'https://7072-prod-d4gi5hg2s057d6cfc-1466119943.tcb.qcloud.la/exercises/single-leg-calf-raise/single-leg-calf-raise.jpg', 'https://7072-prod-d4gi5hg2s057d6cfc-1466119943.tcb.qcloud.la/exercises/single-leg-calf-raise/single-leg-calf-raise.gif', '["单脚前掌踩住踏板边缘，另一腿抬起并轻扶支撑物。","保持膝盖近乎伸直，让工作侧脚跟缓慢下沉。","用前脚掌推起身体至最高点，控制下降后换腿。"]', '["不要用手臂拉动身体。","平衡不足时先使用双腿版本。"]', 55, 1),
    ('ab-wheel-rollout', '腹肌轮', '核心', '腹肌轮', '中级', '["腹直肌","腹横肌"]', '["腹斜肌","背阔肌","前锯肌"]', 'https://7072-prod-d4gi5hg2s057d6cfc-1466119943.tcb.qcloud.la/exercises/ab-wheel-rollout/ab-wheel-rollout.jpg', 'https://7072-prod-d4gi5hg2s057d6cfc-1466119943.tcb.qcloud.la/exercises/ab-wheel-rollout/ab-wheel-rollout.gif', '["双膝跪在垫上，双手握住腹肌轮并置于肩部下方。","收紧腹臀，将轮子缓慢向前推出并保持腰背中立。","到达可控位置后用核心拉回轮子，回到跪姿起点。"]', '["腰部下沉时立即缩短幅度。","不要只用手臂快速拉回轮子。"]', 56, 1),
    ('cable-crunch', '高位绳索卷腹', '核心', '龙门架高位滑轮', '初级', '["腹直肌"]', '["腹斜肌"]', 'https://7072-prod-d4gi5hg2s057d6cfc-1466119943.tcb.qcloud.la/exercises/cable-crunch/cable-crunch.jpg', 'https://7072-prod-d4gi5hg2s057d6cfc-1466119943.tcb.qcloud.la/exercises/cable-crunch/cable-crunch.gif', '["面向高位滑轮跪下，将绳头固定在头部两侧。","保持髋部基本不动，用腹部将胸廓卷向骨盆。","在底端收紧腹部，随后控制脊柱回到中立位。"]', '["不要用手臂向下拉绳索。","避免把动作变成大幅屈髋。"]', 57, 1),
    ('cable-woodchop', '绳索伐木', '核心', '龙门架', '中级', '["腹外斜肌","腹内斜肌"]', '["腹直肌","腹横肌"]', 'https://7072-prod-d4gi5hg2s057d6cfc-1466119943.tcb.qcloud.la/exercises/cable-woodchop/cable-woodchop.jpg', 'https://7072-prod-d4gi5hg2s057d6cfc-1466119943.tcb.qcloud.la/exercises/cable-woodchop/cable-woodchop.gif', '["侧对高位滑轮站立，双手握柄并置于靠近滑轮的肩侧。","转动躯干和脚掌，将手柄斜向拉至对侧髋部。","保持核心受控，沿原路线回到高位后换边。"]', '["不要只靠手臂拉动重量。","膝盖与脚尖随转体自然转动。"]', 58, 1),
    ('hanging-knee-raise', '悬垂举膝', '核心', '单杠或罗马椅', '中级', '["腹直肌"]', '["髂腰肌","腹斜肌"]', 'https://7072-prod-d4gi5hg2s057d6cfc-1466119943.tcb.qcloud.la/exercises/hanging-knee-raise/hanging-knee-raise.jpg', 'https://7072-prod-d4gi5hg2s057d6cfc-1466119943.tcb.qcloud.la/exercises/hanging-knee-raise/hanging-knee-raise.gif', '["双手握住单杠稳定悬垂，双腿自然并拢。","收紧腹部并卷动骨盆，将双膝平稳抬向胸部。","控制双腿回到垂直位置，身体停止摆动后重复。"]', '["不要通过前后摆动甩起双腿。","握力或肩部不稳时使用罗马椅版本。"]', 59, 1),
    ('dead-hang', '单杠悬垂', '核心', '单杠', '初级', '["前臂屈肌群"]', '["背阔肌","肩袖肌群"]', 'https://7072-prod-d4gi5hg2s057d6cfc-1466119943.tcb.qcloud.la/exercises/dead-hang/dead-hang.jpg', 'https://7072-prod-d4gi5hg2s057d6cfc-1466119943.tcb.qcloud.la/exercises/dead-hang/dead-hang.gif', '["双手与肩同宽握住单杠，双脚离地并保持身体垂直。","手臂自然伸直，让肩胛在可控范围内上提并保持呼吸。","达到目标时间后先踩回支撑物，再松开双手。"]', '["肩部疼痛或不稳时不要完全放松悬垂。","不要在握力耗尽后直接跳落。"]', 60, 1);

